builds:
  -
    id: lokalise2
    env:
      - CGO_ENABLED=0
    binary: lokalise2
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - format_overrides:
      - goos: windows
        format: zip

    name_template: 'lokalise2_{{ .Os }}_{{ if eq .Arch "386" }}i386{{ else }}{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - none*

brews:
  - tap:
      owner: lokalise
      name: homebrew-cli-2
    folder: Formula
    homepage: "https://github.com/lokalise/lokalise-cli-2-go"
    description: "Lokalise CLI v2"
    skip_upload: false
    name: lokalise2
    install: |
      bin.install "lokalise2"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

dockers:
  - image_templates:
      - "docker.io/lokalise/lokalise-cli-2:{{ .Tag }}-amd64"
      - "ghcr.io/lokalise/lokalise-cli-2:{{ .Tag }}-amd64"
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "docker.io/lokalise/lokalise-cli-2:{{ .Tag }}-arm64v8"
      - "ghcr.io/lokalise/lokalise-cli-2:{{ .Tag }}-arm64v8"
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "docker.io/lokalise/lokalise-cli-2:{{ .Tag }}"
    image_templates:
      - "docker.io/lokalise/lokalise-cli-2:{{ .Tag }}-arm64v8"
      - "docker.io/lokalise/lokalise-cli-2:{{ .Tag }}-amd64"
  - name_template: "docker.io/lokalise/lokalise-cli-2:latest"
    image_templates:
      - "docker.io/lokalise/lokalise-cli-2:{{ .Tag }}-arm64v8"
      - "docker.io/lokalise/lokalise-cli-2:{{ .Tag }}-amd64"
  - name_template: "ghcr.io/lokalise/lokalise-cli-2:{{ .Tag }}"
    image_templates:
      - "ghcr.io/lokalise/lokalise-cli-2:{{ .Tag }}-arm64v8"
      - "ghcr.io/lokalise/lokalise-cli-2:{{ .Tag }}-amd64"
  - name_template: "ghcr.io/lokalise/lokalise-cli-2:latest"
    image_templates:
      - "ghcr.io/lokalise/lokalise-cli-2:{{ .Tag }}-arm64v8"
      - "ghcr.io/lokalise/lokalise-cli-2:{{ .Tag }}-amd64"

release:
  github:
    owner: lokalise
    name: lokalise-cli-2-go
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  target_commitish: "{{ .Commit }}"
  prerelease: auto
  make_latest: true
  mode: append
  name_template: "Release {{ .Tag }}"
