FROM alpine:3.18.4 as certs
RUN apk --update add ca-certificates

FROM scratch
ENV PATH=/bin
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY lokalise2 /bin/lokalise2

CMD ["/bin/lokalise2"]
